name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r check-requirements.txt
      - name: run checks
        run: flake8 telcell/
